### ISSUE TITLE
Query on CTSimSiam loss

### ISSUE THREAD

**Issue by shrimonmuke0202** [RishikeshMagar/Crystal-Twins#1]
Hi,

In your paper, you used $CT_{SimSiam}$ loss, but I could not find the implementation of it in your code, only $CT_{Barlow}$ loss is implemented. I could not reproduce the result for $CT_{SimSiam}$.

**Comment by RishikeshMagar** [comment]
Hi,
Thank you bringing this to our notice. I will update the SimSiam code soon

**Comment by RishikeshMagar** [comment]
Added the SimSiam Code. Sorry about the delay. Good luck. 

I am closing the issue feel free to reopen if needed
